
;==============================
;
; UNDERSTANDING HDMA MODULES
;
;==============================

; HDMA modules are split into 4 main components
; the first component is the HDMA module itself
; a module contains a 5 byte header followed by an arbitry amount of data
; the first 2 bytes of the header are written to $43x0 and $43x1
; the next 3 bytes are a 24-bit pointer to the next component: the module engine

; a module engine is responsible for interpreting the arbitry data in the module and transcribing it to a proper HDMA table in SNES WRAM
; the module engine is a routine called by the SNES
; it can be further split into the last 2 primary components: the logic engine and the transcription engine

; the logic engine is run by SA-1 and takes over the task of interpreting input data
; the transcription engine is run by SNES from inside its WRAM to let SA-1 operate at full speed
; it is responsible for taking data generated by the logic engine and outputting it into a proper HDMA table

; most module engines run in MPU mode: SA-1 interprets data and SNES outputs it
; however, a module engine can be written to be run by solo SNES, which is useful in case the logic is very simple
; in MPU mode, the following protocol is used:
;	- 2 buffers on dp are used to send data from SA-1 to SNES, minimizing write/read time
;	- !HDMA_ProgramState can be in 2 main states: SA-1 writing to buffer 1 or buffer 2
;	- the highest bit in the lo byte is set when SNES is waiting to read a new buffer, which is a requirement for SA-1 to update program state
;	- this method strategically allocates wait time and leaves no opening for the CPUs to desync











;==============================
;
; HDMA MODULES
;
;==============================

;=========================;
; MULTI-COMPONENT MODULES ;
;=========================;

	WaterProjection:
	db $03,$2111			; mode 3 - > 2111
	dl Engine_WaterProjection	; code pointer
	.Data
	..header
	dw $0080			; dummy coord
	dw ..coords-..factors		; table length
	dw ..coords			; location of coordinate table
	; factor for scrolling used for each chunk
	..factors
	dw $0015	; 0
	dw $0033	; 1
	dw $0050	; 2
	dw $006D	; 3
	dw $008B	; 4
	dw $00A8	; 5
	dw $00C5	; 6
	dw $00E3	; 7
	dw $0100	; 8
	dw $011D	; 9
	dw $013B	; A
	dw $0158	; B
	; Y coord (within BG3) to use for each chunk
	..coords
	dw $0000	; 0
	dw $0006	; 1
	dw $000C	; 2
	dw $0012	; 3
	dw $0018	; 4
	dw $001E	; 5
	dw $0024	; 6
	dw $002A	; 7
	dw $0030	; 8
	dw $0036	; 9
	dw $003C	; A
	dw $0058	; B




; it really might be a good idea to have this table include more data
; for example... why not give each chunk its own set y coordinate? that would probably be better than just adding 8 for each chunk
; additionally, i think each chunk should be able to set its own priority and also hold a palette entry




	WaterSkyGradient:
	db $03,$2121			; mode 3 -> 2121
	dl Engine_WaterSkyGradient	; code pointer
	.Data
	..header
	dw ..skygradient
	dw ..extendedgradient
	..skygradient			; starts at top of screen, cut off by projection
	db $08 : %snescolor(0, 2, 11)
	db $08 : %snescolor(0, 2, 11)
	db $08 : %snescolor(0, 3, 12)
	db $08 : %snescolor(0, 3, 12)
	db $08 : %snescolor(0, 4, 12)
	db $08 : %snescolor(0, 4, 13)
	db $08 : %snescolor(0, 5, 13)
	db $08 : %snescolor(0, 5, 13)
	db $08 : %snescolor(0, 6, 14)
	db $08 : %snescolor(0, 6, 14)
	db $08 : %snescolor(2, 7, 14)
	db $08 : %snescolor(4, 7, 15)
	db $08 : %snescolor(6, 8, 15)
	db $08 : %snescolor(8, 8, 15)
	db $00
	..extendedgradient		; starts at projection and continues for rest of screen
	db $01 : %snescolor(11, 11, 11)
	db $00




	WaterGradient:
	db $03,$2121			; mode 3 -> 2121
	dl Engine_WaterGradient
	db $1D				; which color to write
	%snescolor(0, 0, 6)		; 0
	%snescolor(0, 1, 6)		; 1
	%snescolor(0, 2, 7)		; 2
	%snescolor(0, 3, 7)		; 3
	%snescolor(0, 4, 8)		; 4
	%snescolor(0, 5, 8)		; 5
	%snescolor(1, 6, 9)		; 6
	%snescolor(3, 7, 9)		; 7
	%snescolor(5, 8, 10)		; 8
	%snescolor(7, 9, 10)		; 9
	%snescolor(9, 10, 11)		; A
	%snescolor(11, 11, 11)		; B
	; table assumed to have one color per chunk




macro indir(label, sub)
	dw <label>_<sub>-<label>
endmacro

	WaterWaveEffect:
	db $43,$210D			; mode 3 indirect -> 210D
	dl Engine_WaterWaveEffect	; code pointer
	.Offsets			; offset data
	..0	dw $0000,$0000
	..1	dw $FFFF,$0000
	..2	dw $FFFF,$0001
	..3	dw $0000,$0001



	WaterPriority:
	db $01,$212C			; mode 1 -> 212C
	dl Engine_WaterPriority		; code pointer
	.Data
	..sky
	db $13,$03			; sky priority (displayed above the first chunk)
	..extended
	db $00,$13			; extended water priority (displayed under the last chunk)
	..chunks
	db $15,$12			; 0
	db $15,$12			; 1
	db $15,$12			; 2
	db $15,$12			; 3
	db $15,$12			; 4
	db $15,$12			; 5
	db $15,$12			; 6
	db $15,$12			; 7
	db $04,$13			; 8
	db $04,$13			; 9
	db $04,$13			; A
	db $04,$13			; B


;	WaterPriorityBG3:
;	db $00,$2105			; mode 0 -> 2105
;	dl Engine_WaterPriorityBG3	; code pointer





;===================;
; PARALLAX MODUELES ;
;===================;
; engines do not account for scanline counts greater than 0x7F
; larger chunks have to be split

	FlowerField:
	db $02,$210F			; mode 2 -> 210F
	dl Engine_Parallax		; code pointer
	dw $077 : %fraction(0, 1)	;\ 0.0000
	dw $078 : %fraction(0, 1)	;/
	dw $030 : %fraction(1, 2)	; 0.4933
	dw $010 : %fraction(11, 20)	; 0.5549
	dw $011 : %fraction(12, 19)	; 0.6243
	dw $019 : %fraction(7, 10)	; 0.7023
	dw $019 : %fraction(15, 19)	; 0.7901
	dw $001 : %fraction(8, 9)	; 0.8888
	dw $0000			; end module


	MountainRange:
	db $02,$210F			; mode 2 -> 210F
	dl Engine_Parallax		; code pointer
	dw $048 : %fraction(0, 1)	;\ 0.0000
	dw $049 : %fraction(0, 1)	;/
	dw $060 : %fraction($0C, $20)	; 0.3750
	dw $020 : %fraction($0E, $20)	; 0.4375
	dw $040 : %fraction($10, $20)	; 0.5000
	dw $010 : %fraction($15, $20)	; 0.6563
	dw $001 : %fraction($18, $20)	; 0.7500
	dw $0000			; end module


	MountainTopsWithClouds:
	db $02,$210F			; mode 2 -> 210F
	dl Engine_Parallax		; code pointer
	dw $070 : %fraction(0, 1)	;\ 0.0000
	dw $070 : %fraction(0, 1)	;/
	dw $040 : %fraction(1, 2)	;\ 0.4933
	dw $040 : %fraction(1, 2)	;/
	dw $010 : %fraction(11, 20)	; 0.5549
	dw $010 : %fraction(12, 19)	; 0.6243
	dw $010 : %fraction(7, 10)	; 0.7023
	dw $010 : %fraction(15, 19)	; 0.7901
	dw $001 : %fraction(8, 9)	; 0.8888
	dw $0000


	StarrySkyWithWall:
	db $02,$210F			; mode 2 -> 210F
	dl Engine_Parallax		; code pointer
	dw $070 : %fraction(0, 1)	;\
	dw $070 : %fraction(0, 1)	; | 0.0000
	dw $06F : %fraction(0, 1)	;/
	dw $001 : %fraction(1, 1)	; 0.5000
	dw $0000

	.ColorMath
	db $00,$2131			; mode 0 -> 2131
	dl Engine_1p1			; code pointer
	db $70,$22			;\
	db $70,$22			; | color math on backdrop + BG2
	db $6F,$22			;/
	db $01,$20			; color math on backdrop only
	db $00				; end table



	IcyMountains:
	db $02,$210F			; mode 2 -> 210F
	dl Engine_Parallax		; code pointer
	dw $078 : %fraction(0, 1)	;\ 0.0000
	dw $078 : %fraction(0, 1)	;/
	dw $040 : %fraction(0, 4)	; 0.2500
	dw $030 : %fraction(0, 2)	; 0.4933
	dw $010 : %fraction(11, 20)	; 0.5549
	dw $010 : %fraction(12, 19)	; 0.6243
	dw $010 : %fraction(7, 10)	; 0.7023
	dw $010 : %fraction(15, 19)	; 0.7901
	dw $001 : %fraction(8, 9)	; 0.8888
	dw $0000


	; NOTE: BG3
	RainyRiver:
	db $02,$2111			; mode 2 -> 2111
	dl Engine_Parallax		; code pointer
	dw $07F : %fraction(1, 1)	;\
	dw $07F : %fraction(1, 1)	; |
	dw $072 : %fraction(1, 1)	;/
	dw $001 : %fraction(1, 1)	;
	dw $0000


	; NOTE: 3D WATER EFFECT NOT DONE



;==================;
; GRADIENT MODULES ;
;==================;
; engines do not account for scanline counts greater than 0x7F
; larger chunks have to be split

	Gradient_Evening:
	.Red
	db $00,$2132	; mode 0 -> 2132
	dl Engine_1p1	; code pointer

	db $0E,$20
	db $0E,$21
	db $0E,$22
	db $0E,$23
	db $0E,$24
	db $0E,$25
	db $0E,$26
	db $0E,$27
	db $0E,$28
	db $0E,$29
	db $0E,$2A
	db $0E,$2B
	db $0E,$2C
	db $0E,$2D
	db $0E,$2E
	db $0E,$2F
	db $0E,$30

	db $0E,$31	; 0
	db $0E,$32	; E
	db $0E,$33	; 1C
	db $0E,$34	; 2A
	db $0E,$35	; 38
	db $0E,$36	; 46
	db $0E,$37	; 54
	db $0E,$38	; 62
	db $0E,$39	; 70
	db $0E,$3A	; 7E
	db $0E,$3B	; 8C
	db $0E,$3C	; 9A
	db $0E,$3D	; A8
	db $1F,$3E	; B6
	db $1F,$3F	; D5
	db $00

	.Green
	db $00,$2132	; mode 0 -> 2132
	dl Engine_1p1	; code pointer
	db $15,$40	; 0
	db $15,$41	; 15
	db $15,$42	; 2A
	db $15,$43	; 3F
	db $15,$44	; 54
	db $15,$45	; 69
	db $15,$46	; 7E
	db $15,$47	; 93
	db $15,$48	; A8
	db $15,$49	; BD
	db $15,$4A	; D2
	db $00
	.Blue

	db $00,$2132	; mode 0 -> 2132
	dl Engine_1p1	; code pointer


	db $1A,$80
	db $1A,$81
	db $1A,$82
	db $1A,$83
	db $1A,$84
	db $1A,$85
	db $1A,$86
	db $1A,$87


	db $1A,$88	; 0
	db $1A,$87	; 1A
	db $1A,$86	; 34
	db $1A,$85	; 4E
	db $1A,$84	; 68
	db $1A,$83	; 82
	db $1A,$82	; 9C
	db $1A,$81	; B6
	db $1A,$80	; D0
	db $00

	.Module
	db $00,$2132			; mode 0 -> 2132
	dl Engine_1p1_GradientRunOnce	; code pointer
	%snescolor(17, 0, 8)		; starting color
	.Single
	db $0E,$31	; 0
	db $07,$32	; E
	db $05,$41	; 15
	db $02,$87	; 1A
	db $0C,$33	; 1C
	db $02,$34	; 28
	db $0A,$42	; 2A
	db $04,$86	; 34
	db $07,$35	; 38
	db $07,$43	; 3F
	db $08,$36	; 46
	db $04,$85	; 4E
	db $02,$37	; 52
	db $0E,$44	; 54
	db $06,$38	; 62
	db $01,$84	; 68
	db $07,$45	; 69
	db $0C,$39	; 70
	db $02,$3A	; 7C
	db $04,$46	; 7E
	db $0A,$83	; 82
	db $07,$3B	; 8C
	db $07,$47	; 93
	db $02,$3C	; 9A
	db $0A,$82	; 9C
	db $02,$3D	; A6
	db $0C,$48	; A8
	db $02,$3E	; B4
	db $07,$81	; B6
	db $03,$49	; BD
	db $02,$80	; D0
	db $03,$4A	; D2
	db $01,$3F	; D5
	db $00


	Gradient_Sunset:
	.Red
	db $70,$3F	; 0
	db $70,$3F	; 70
	db $00
	.Green
	db $13,$4B	; 0
	db $13,$4C	; 13
	db $13,$4D	; 26
	db $13,$4E	; 39
	db $13,$4F	; 4C
	db $13,$50	; 5F
	db $13,$51	; 72
	db $13,$52	; 85
	db $13,$53	; 98
	db $13,$54	; AB
	db $13,$55	; BE
	db $13,$56	; D1
	db $00
	.Blue
	db $20,$86	; 0
	db $20,$85	; 20
	db $20,$84	; 40
	db $20,$83	; 60
	db $20,$82	; 80
	db $20,$81	; A0
	db $20,$80	; C0
	db $00

	.Module
	db $00,$2132			; mode 0 -> 2132
	dl Engine_1p1_GradientRunOnce	; code pointer
	%snescolor(31, 11, 6)		; starting color
	.Single
	db $13,$86	; 0
	db $0D,$4C	; 13
	db $06,$85	; 20
	db $13,$4D	; 26
	db $07,$4E	; 39
	db $0C,$84	; 40
	db $13,$4F	; 4C
	db $01,$50	; 5F
	db $10,$83	; 60
	db $02,$3F	; 70
	db $0E,$51	; 72
	db $05,$82	; 80
	db $13,$52	; 85
	db $08,$53	; 98
	db $0B,$81	; A0
	db $13,$54	; AB
	db $02,$55	; BE
	db $11,$80	; C0
	db $01,$56	; D1
	db $00


	Gradient_BlueSky:
	.Red
	db $0C,$29	; 0
	db $0C,$2A	; C
	db $0C,$2B	; 18
	db $0C,$2C	; 24
	db $0C,$2D	; 30
	db $0C,$2E	; 3C
	db $0C,$2F	; 48
	db $0C,$30	; 54
	db $0C,$31	; 60
	db $0C,$32	; 6C
	db $00
	.Green
	db $0E,$54	; 0
	db $0E,$55	; E
	db $0E,$56	; 1C
	db $0E,$57	; 2A
	db $0E,$58	; 38
	db $0E,$59	; 46
	db $0E,$5A	; 54
	db $0E,$5B	; 62
	db $0E,$5C	; 70
	db $00
	.Blue
	db $26,$99	; 00
	db $26,$9A	; 26
	db $26,$9B	; 4C
	db $00

	.Module
	db $00,$2132			; mode 0 -> 2132
	dl Engine_1p1_GradientRunOnce	; code pointer
	%snescolor(9, 20, 25)		; starting color
	.Single
	db $0C,$29	; 0
	db $02,$2A	; C
	db $0A,$55	; E
	db $04,$2B	; 18
	db $08,$56	; 1C
	db $02,$2C	; 24
	db $04,$9A	; 26
	db $06,$57	; 2A
	db $08,$2D	; 30
	db $04,$58	; 38
	db $0A,$2E	; 3C
	db $02,$59	; 46
	db $04,$2F	; 48
	db $06,$9B	; 4C
	db $02,$30	; 52
	db $0C,$5A	; 54
	db $02,$31	; 60
	db $0A,$5B	; 62
	db $04,$32	; 6C
	db $01,$5C	; 70
	db $00


	Gradient_Nighttime:
	.Red
	db $00,$2132	; mode 0 -> 2132
	dl Engine_1p1	; code pointer
	db $01,$20	; 00
	db $00

	.Green
	db $00,$2132	; mode 0 -> 2132
	dl Engine_1p1	; code pointer
	db $26,$40	; 00
	db $26,$41	; 26
	db $26,$42	; 4C
	db $26,$43	; 72
	db $26,$44	; 98
	db $26,$45	; BE
	db $00

	.Blue
	db $00,$2132	; mode 0 -> 2132
	dl Engine_1p1	; code pointer
	db $0C,$80	; 0
	db $0C,$81	; C
	db $0C,$82	; 18
	db $0C,$83	; 24
	db $0C,$84	; 30
	db $0C,$85	; 3C
	db $0C,$86	; 48
	db $0C,$87	; 54
	db $0C,$88	; 60
	db $0C,$89	; 6C
	db $0C,$8A	; 78
	db $0C,$8B	; 84
	db $0C,$8C	; 90
	db $0C,$8D	; 9C
	db $0C,$8E	; A8
	db $0C,$8F	; B4
	db $0C,$90	; C0
	db $0C,$91	; CC
	db $00

	.Module
	db $00,$2132			; mode 0 -> 2132
	dl Engine_1p1_GradientRunOnce	; code pointer
	%snescolor(0, 0, 0)		; starting color
	.Single
	db $0C,$E0	; 0
	db $0C,$81	; C
	db $0C,$82	; 18
	db $02,$83	; 24
	db $0A,$41	; 26
	db $0C,$84	; 30
	db $0C,$85	; 3C
	db $04,$86	; 48
	db $08,$42	; 4C
	db $0C,$87	; 54
	db $0C,$88	; 60
	db $06,$89	; 6C
	db $06,$43	; 72
	db $0C,$8A	; 78
	db $0C,$8B	; 84
	db $08,$8C	; 90
	db $04,$44	; 98
	db $0C,$8D	; 9C
	db $0C,$8E	; A8
	db $0A,$8F	; B4
	db $02,$45	; BE
	db $0C,$90	; C0
	db $01,$91	; CC
	db $00



	DarknessEffect:
	db $00,$2100
	dl Engine_Darkness
	db $02,$00
	db $02,$01
	db $02,$02
	db $02,$03
	db $02,$04
	db $02,$05
	db $02,$06
	db $02,$07
	db $02,$08
	db $02,$09
	db $02,$0A
	db $02,$0B
	db $02,$0C
	db $02,$0D
	db $02,$0E
	db $4D,$0F
	db $4D,$0F
	db $02,$0E
	db $02,$0D
	db $02,$0C
	db $02,$0B
	db $02,$0A
	db $02,$09
	db $02,$08
	db $02,$07
	db $02,$06
	db $02,$05
	db $02,$04
	db $02,$03
	db $02,$02
	db $02,$01
	db $02,$00
	db $00



;========================;
; DIRECT CONTROL MODULES ;
;========================;

	DirectControl:
	.BG1
	db $03,$210D		; mode 3 -> 210D
	dl ..code		; nested engine
	..code
		LDA !HDMA2location+1,x : STA $00+1
		LDA !HDMA2counter,x
		AND #$0001 : BEQ +
		LDA !HDMA2size,x
	+	CLC : ADC !HDMA2location,x
		STA $00

		LDY #$01
		LDA $1A : STA [$00],y
		LDY #$03
		LDA $1C
		CLC : ADC $7888
		STA [$00],y

		SEP #$20
		INC !HDMA2counter,x
		LDY #$05
		LDA #$00
		STA [$00]
		STA [$00],y

		REP #$20
		LDA $00 : STA !HDMA2source,x
		RTL



;==============;
; MISC MODULES ;
;==============;

	CutsceneSmoothness:
	db $00,$2100		; mode 0 -> 2100
	dl Engine_CutsceneSmoothness
	.Pointers
		dw ..0
		dw ..1
		dw ..2
		dw ..3
		dw ..4
		dw ..5
		dw ..6
		dw ..7
		dw ..8
		..1
		db $02,$80
		db $6D,$0F
		db $6D,$0F
		db $01,$80
		..0
		db $00
		..2
		db $04,$80
		db $6B,$0F
		db $6B,$0F
		db $01,$80
		db $00
		..3
		db $06,$80
		db $69,$0F
		db $69,$0F
		db $01,$80
		db $00
		..4
		db $08,$80
		db $67,$0F
		db $67,$0F
		db $01,$80
		db $00
		..5
		db $0A,$80
		db $65,$0F
		db $65,$0F
		db $01,$80
		db $00
		..6
		db $0C,$80
		db $63,$0F
		db $63,$0F
		db $01,$80
		db $00
		..7
		db $0E,$80
		db $61,$0F
		db $61,$0F
		db $01,$80
		db $00
		..8
		db $10,$80
		db $5F,$0F
		db $5F,$0F
		db $01,$80
		db $00




	DizzyEffect_BG1:
	db $03,$210D		; mode 3 -> 210D
	dl Engine_DizzyEffect_BG1
	.ColorTable
	%snescolor(0, 0, 0)
	%snescolor(0, 0, 2)
	%snescolor(0, 0, 3)
	%snescolor(0, 0, 4)
	%snescolor(0, 0, 5)
	%snescolor(0, 0, 6)
	%snescolor(0, 0, 7)
	%snescolor(0, 0, 8)
	%snescolor(0, 0, 7)
	%snescolor(0, 0, 6)
	%snescolor(0, 0, 5)
	%snescolor(0, 0, 4)
	%snescolor(0, 0, 3)
	%snescolor(0, 0, 2)
	%snescolor(0, 0, 1)
	%snescolor(0, 0, 0)
	%snescolor(1, 0, 0)
	%snescolor(2, 0, 0)
	%snescolor(3, 0, 0)
	%snescolor(4, 0, 0)
	%snescolor(5, 0, 0)
	%snescolor(6, 0, 0)
	%snescolor(7, 0, 0)
	%snescolor(8, 0, 0)
	%snescolor(7, 0, 0)
	%snescolor(6, 0, 0)
	%snescolor(5, 0, 0)
	%snescolor(4, 0, 0)
	%snescolor(3, 0, 0)
	%snescolor(2, 0, 0)
	%snescolor(1, 0, 0)
	%snescolor(0, 0, 0)


	DizzyEffect_BG2:
	db $02,$2110			; mode 2 -> 2110
	dl Engine_DizzyEffect_BG2	; code pointer
	; data ripped from yoshi's island
	db $0D,$0E,$0E,$0F,$0F,$10,$10,$11
	db $11,$11,$12,$12,$13,$13,$13,$14
	db $14,$14,$14,$15,$15,$15,$15,$15
	db $15,$15,$16,$16,$16,$15,$15,$15
	db $15,$15,$15,$15,$14,$14,$14,$14
	db $13,$13,$13,$12,$12,$11,$11,$11
	db $10,$10,$0F,$0F,$0E,$0E,$0D,$0D
	db $0C,$0C,$0B,$0B,$0A,$09,$09,$08
	db $08,$07,$07,$06,$06,$05,$05,$04
	db $04,$04,$03,$03,$02,$02,$02,$01
	db $01,$01,$01,$00,$00,$00,$00,$00
	db $00,$00,$00,$00,$00,$00,$00,$00
	db $00,$00,$00,$00,$01,$01,$01,$01
	db $02,$02,$02,$03,$03,$04,$04,$04
	db $05,$05,$06,$06,$07,$07,$08,$08
	db $09,$09,$0A,$0B,$0B,$0C,$0C,$0D
	.End





	FogOfWar:
	db $00,$2100
	dl Engine_FogOfWar
	dw $68F			; fog top
	dw $FFFF		; fog bottom




;==============================
;
; MODULE CODE POINTERS
;
;==============================
; when a code pointer is called, SNES is in the following state:
; DP	3000
; B	generic (not K)
; $00	24-bit pointer to module (data starts at [$00],5)
; A	16-bit
; index	8-bit
; X	channel index
; Y	3
; any modification to the $00 pointer will be taken into account by the transcription engine
; they also require X = channel index to be intact

; in MPU mode, modules use DP $3100
; the first 64 bytes ($00-$3F) can be used by both CPUs
; see Defines.asm for memory map






; handles data that has 1 scanline byte and 1 data byte
; mem+0 holds a 16-bit scroll offset
; mem+2 holds an 8-bit stretch value (this is autmatically set to 0 for channel 7)
	Engine_1p1:
		.Main
		LDA !HDMA2mem,x : STA $3100
		CPX #$50 : BNE ..getstretch
		LDA #$0000 : BRA ..setstretch
		..getstretch
		LDA !HDMA2mem+2,x
		AND #$00FF
		..setstretch
		STA $3102
		LDA.w #Logic_HDMA_1p1 : STA $3180
		LDA.w #Logic_HDMA_1p1>>8 : STA $3181
		JSR.w MPU_HDMA_1p1
		RTL

		.Gradient
		LDY #$05
		LDA [$00],y : STA !2132_RGB
		INC $00
		INC $00
		BRA .Main

		.GradientRunOnce
		LDY #$05
		LDA [$00],y : STA !2132_RGB
		INC $00
		INC $00

		.RunOnce
		LDA !HDMA2init,x
		AND #$00FF : BEQ .Main
		RTL


	Engine_Parallax:
		LDA !HDMA2init,x
		AND #$00FF : BEQ .Run
		SEP #$20
		LDA $20 : XBA
		LDA $1E
		REP #$20
		CMP !HDMA2mem,x
		STA !HDMA2mem,x
		BEQ .Return

		.Run
		LDA.w #Logic_BG2Parallax : STA $3180
		LDA.w #Logic_BG2Parallax>>8 : STA $3181
		JSR.w MPU_HDMA_1p2

		.Return
		RTL


	Engine_Darkness:
		LDA !HDMA2init,x
		AND #$00FF : BEQ .Run
		LDA !2100
		AND #$00FF
		CMP #$0080
		BCC $03 : LDA #$0000
		CMP !HDMA2mem,x : BEQ .Return
		STA !HDMA2mem,x

		.Run
		LDA.w #Logic_Darkness : STA $3180
		LDA.w #Logic_Darkness>>8 : STA $3181
		JSR.w MPU_HDMA_1p1

		.Return
		RTL



	Engine_FogOfWar:
		PHB

		.GetPlayer1
		LDY !P2Status-$80 : BNE ..cantsee
		LDA !P2YPosLo-$80 : BPL ..set
		LDA #$0000 : BRA ..set
		..cantsee
		LDA #$FFFF
		..set
		STA $06

		.GetPlayer2
		LDY !P2Status : BNE ..cantsee
		LDA !P2YPosLo : BPL ..set
		LDA #$0000 : BRA ..set
		..cantsee
		LDA #$FFFF
		..set
		STA $08

		; $06 = player 1 Y
		; $08 = player 2 Y
		; if any of these are negative, that player can not see in fog of war
		.ProcessFog
		LDA $00+1 : STA $03+1			; hi byte of pointer
		LDA $00					;\
		CLC : ADC #$0005			; | [$00] = top of fog of war
		STA $00					; | [$03] = bottom of fog of war
		INC #2 : STA $03			;/
		..checkp1				;\
		LDA $06 : BMI ..checkp2			; |
		CMP [$00] : BCC ..checkp2		; |
		CMP [$03] : BCC ..translucentfog	; | if a player is within the fog, it can be seen through
		..checkp2				; |
		LDA $08 : BMI ..solidfog		; |
		CMP [$00] : BCC ..solidfog		; |
		CMP [$03] : BCS ..solidfog		;/
		..translucentfog			;\
		SEP #$20				; |
		LDA !HDMA2init,x : BEQ ..done		; |
		LDA !HDMA2mem,x				; |
		CMP #$08 : BEQ ..done			; |
		INC !HDMA2mem,x				; | update fog opacity
		BRA ..done				; | (snaps on init, ticks on main)
		..solidfog				; |
		SEP #$20				; |
		LDA !HDMA2init,x : BNE +		; |
		STZ !HDMA2mem,x : BRA ..done		; |
	+	LDA !HDMA2mem,x : BEQ ..done		; |
		DEC !HDMA2mem,x				; |
		..done					;/


		.CapFog
		LDA !2100				;\
		BPL $02 : LDA #$00			; |
		CMP !HDMA2mem,x : BCS ..done		; | fog is not allowed to be brighter than screen
		STA !HDMA2mem,x				; |
		..done					;/



		.GetWriteIndex
		LDA !HDMA2location+2,x : PHA : PLB	; switch to write bank
		REP #$30				; all regs 16-bit
		LDA !HDMA2counter,x			;\
		AND #$0001 : BEQ +			; |
		LDA !HDMA2size,x			; | double buffer table address
	+	CLC : ADC !HDMA2location,x		; |
		TAY					;/
		PHY					; push for later



	.DrawFog
		LDA [$00]				;\
		SEC : SBC $1C				; | check fog top
		BPL $03 : JMP .TopAbove			; |
		CMP !HDMA_MaxY : BCS .OffScreen		;/

		.TopVisible
		CMP #$0080 : BCS ..2chunks		;\
		..1chunk				; |
		SEP #$20				; |
		STA $0000,y : INY			; |
		BRA ..finishtop				; |
		..2chunks				; |
		SEP #$20				; | draw visible area above fog
		LSR A : STA $0000,y : INY		; |
		BCC $01 : INC A				; |
		XBA					; |
		LDA !2100 : STA $0000,y : INY		; |
		XBA : STA $0000,y : INY			; |
		..finishtop				; |
		LDA !2100 : STA $0000,y : INY		;/

		.ComplexDraw
		REP #$20				;\
		LDA [$03]				; | check fog bottom
		SEC : SBC $1C				; |
		CMP !HDMA_MaxY : BCC ..calcbottom	;/
		..finishwithfog				;\
		SEP #$20				; | if bottom isn't visible, simply extend fog to the bottom of the screen
		LDA #$01 : STA $0000,y : INY		; |
		LDA !HDMA2mem,x : JMP .EndTable		;/
		..calcbottom				;\
		CMP #$0080 : BCS ..2chunks		; |
		..1chunk				; |
		SEP #$20				; |
		STA $0000,y : INY			; |
		BRA ..finishvisible			; |
		..2chunks				; | draw fog
		SEP #$20				; |
		LSR A : STA $0000,y : INY		; |
		BCC $01 : INC A				; |
		XBA					; |
		LDA !HDMA2mem,x : STA $0000,y : INY	; |
		XBA : STA $0000,y : INY			;/
		..finishvisible				;\
		LDA !HDMA2mem,x : STA $0000,y : INY	; | if bottom is visible, end fog
		LDA #$01 : STA $0000,y : INY		; |
		LDA !2100 : BRA .EndTable		;/


		.OffScreen
		SEP #$20
		LDA #$01 : STA $0000,y : INY
		LDA !2100 : BRA .EndTable


		.TopAbove
		LDA [$03]				;\
		SEC : SBC $1C				; | check fog bottom
		BMI .OffScreen				; |
		CMP !HDMA_MaxY : BCC ..calcbottom	;/
		..coverwholescreen			;\
		SEP #$20				; | exception if fog covers whole screen
		LDA #$01 : STA $0000,y : INY		; |
		LDA !HDMA2mem,x : BRA .EndTable		;/
		..calcbottom				;\
		CMP #$0080 : BCS ..2chunks		; |
		..1chunk				; |
		SEP #$20				; |
		STA $0000,y : INY			; |
		BRA ..finishtable			; |
		..2chunks				; |
		SEP #$20				; |
		LSR A : STA $0000,y : INY		; | draw fog
		BCC $01 : INC A				; |
		XBA					; |
		LDA !HDMA2mem,x : STA $0000,y : INY	; |
		XBA : STA $0000,y : INY			; |
		..finishtable				; |
		LDA !HDMA2mem,x : STA $0000,y : INY	; |
		LDA #$01 : STA $0000,y : INY		; |
		LDA !2100				;/


		.EndTable
		STA $0000,y : INY			; final brightness value
		LDA #$00 : STA $0000,y			; end table
		INC !HDMA2counter,x			; increment internal counter
		LDA $0D+2 : STA $4324,x			; update hardware bank
		REP #$20				;\ update hardware mirror
		PLA : STA !HDMA2source,x		;/
		SEP #$10				; index 8-bit
		PLB
		RTL					; return






	Engine_CutsceneSmoothness:
		LDA !CutsceneSmoothness
		AND #$00FF
		ASL A
		ADC #$0005
		TAY
		LDA [$00],y : STA !HDMA2source,x
		SEP #$20
		LDA $00+2 : STA $4324,x
		REP #$20
		.Return
		RTL





; this one sets its output table to !DecompBuffer+$1000 on init
; this is required so sprites can check for displacement without using pointers
; its size is also set to 0x40
	Engine_DizzyEffect_BG1:
		LDA !HDMA2init,x
		AND #$00FF : BNE .Main

		.Init
		LDA.w #!DecompBuffer+$1000 : STA !HDMA2location,x
		LDA.w #!DecompBuffer+$1000>>8 : STA !HDMA2location+1,x
		SEP #$20
		XBA : STA $4324,x
		REP #$20
		LDA #$0040 : STA !HDMA2size,x

		.Main
		LDA !Level+2 : BEQ .Disable
		LDA !StarTimer
		AND #$00FF : BEQ .Run

		.Star
		STZ !Level+2

		.Disable
		SEP #$20
		LDA !DizzyEffect : BEQ ..process
		LDA #$00 : STA !DizzyEffect
		LDA #$40 : STA !SPC4			; dizzy OFF!! SFX
		..process
		LDA !HDMA2bit,x : TRB !HDMA
		LDA #$01 : STA !2105
		REP #$20
		RTL

		.Run
		LDA.w #Logic_DizzyEffect_BG1 : STA $3180
		LDA.w #Logic_DizzyEffect_BG1>>8 : STA $3181
		JSR.w MPU_InterlacedData_16

		LDA !HDMA2location+1,x : STA $03+1
		LDA !HDMA2counter,x
		AND #$0001
		BEQ $03 : LDA #$0008
		CLC
		ADC !HDMA2size,x
		ADC !HDMA2size,x
		ADC !HDMA2location,x
		STA $03

		LDY #$01
		LDA $1A : STA [$03],y
		LDY #$03
		LDA $00 : STA [$03],y

		SEP #$20
		LDA #$01 : STA [$03]
		LDY #$05
		LDA #$00 : STA [$03],y

		LDA #$02 : STA !2105
		REP #$20
		LDA $03 : STA !HDMA2source,x

		PHX
		TXY
		JSL GetVRAM
		LDA #$0080 : STA !VRAMbase+!VRAMtable+$00,x
		LDA !HDMA2location,y : STA !VRAMbase+!VRAMtable+$02,x
		LDA !HDMA2location+1,y : STA !VRAMbase+!VRAMtable+$03,x
		LDA.l !2109						;\
		AND #$00FC						; | layer 3 address
		XBA : STA !VRAMbase+!VRAMtable+$05,x			;/
		PLX

		RTL



	Engine_DizzyEffect_BG2:
		LDA !StarTimer						;\
		AND #$00FF : BNE .Disable				; | disable effect if player has star or dizzy intensity is 0
		LDA !Level+2 : BEQ .Disable				;/

		.DisableOtherChannels
		PHX							; preserve X
		..loop							;\
		TXA							; |
		SEC : SBC #$0010					; | loop through lower channels
		BMI ..done						; |
		TAX							;/
		LDA !HDMA2module,x : BEQ ..loop				;\
		STA $03							; |
		LDA !HDMA2module+1,x : STA $03+1			; |
		LDY #$01						; | search for channels writing to BG2 scroll
		LDA [$03],y						; |
		AND #$00FF						; |
		CMP #$000F : BEQ ..disable				; |
		CMP #$0010 : BNE ..loop					;/
		..disable						;\
		LDA !HDMA2bit,x						; |
		AND #$00FF : TRB !HDMA					; | disable lower channels writing to BG2 scroll
		BRA ..loop						; |
		..done							;/
		PLX							; restore X

		.Run
		INC !HDMA2mem,x
		LDA $1A
		CLC : ADC !HDMA2mem,x
		STA $1E
		LDA.w #Logic_DizzyEffect_BG2 : STA $3180
		LDA.w #Logic_DizzyEffect_BG2>>8 : STA $3181
		JSR.w MPU_HDMA_1p2
		RTL

		.Disable
		STZ !HDMA2mem,x
		LDA !HDMA2bit,x
		AND #$00FF : TRB !HDMA
		RTL






; leaves water level data in RAM, which other effects can use
	Engine_WaterProjection:
		LDA !IceLevel						;\
		AND #$00FF : BNE +					; |
		LDA $14							; | scroll water horizontally unless frozen
		AND #$0003 : BNE +					; |
		INC !Level+4						;/
	+	LDA $1C							;\
		SEC : SBC !Level+2					; > position of water on screen
		CLC : ADC #$0030					; > -height of water image
		CMP #$0100 : BCC +					; | clamp BG3 y position to prevent vertical wrapping
		CMP #$FF00 : BCS +					; |
		LDA #$0100						;/
	+	STA $24							; BG3 Y
		STA $3124
		LDA $1A							;\
		CLC : ADC !Level+4					; | BG3 X
		STA $22							;/
		STA $3122

		LDA.w #Logic_BG3Projection : STA $3180
		LDA.w #Logic_BG3Projection>>8 : STA $3181
		JSR.w MPU_HDMA_1p4
		RTL


; must be run after water projection
	Engine_WaterPriority:
		LDA.w #Logic_ProjectionPriority : STA $3180
		LDA.w #Logic_ProjectionPriority>>8 : STA $3181
		JSR.w MPU_HDMA_1p2
		RTL


; must be run after water projection
; scratch:
;	$00	16-bit copy of !2105 (read from DP)
;	Engine_WaterPriorityBG3:
;		PHD
;		PHX
;		LDA !2105-1 : AND #$FF00 : PHA			; get screen mode (in hi byte)
;		LDA #$3100 : TCD
;
;		LDA !HDMA2counter,x
;		AND #$0001 : BEQ +
;		LDA !HDMA2size,x
;	+	CLC : ADC !HDMA2location,x
;		STA !HDMA_Output
;		SEP #$20
;		INC !HDMA2counter,x
;		LDA !HDMA2location+2,x : STA !HDMA_Output+2
;		REP #$20
;
;		LDY #$00					; index 0
;		STZ !HDMA_WorkingY				; start from scanline 0
;		PLA : STA $00
;
;		LDA !Level+2
;		SEC : SBC $1C
;		BMI .SuperHigh
;		CMP #$00E0 : BCS .End
;		CMP #$0070 : BCC .High
;
;	.Low
;		CMP #$0080 : BCC ..chunk2
;		..chunk1
;		LSR A
;		PHA
;		BCC $01 : INC A
;		ORA $00
;		AND #$F7FF : STA [!HDMA_Output],y : INY #2
;		PLA
;		..chunk2
;		ORA $00
;		AND #$F7FF : STA [!HDMA_Output],y : INY #2 
;		LDA $00
;		ORA #$0801
;		BRA .Write
;
;	.High
;		ORA $00
;		ORA #$0800 : STA [!HDMA_Output],y : INY #2
;		LDA $00
;		AND #$F7FF
;		ORA #$0001
;		BRA .Write
;
;	.SuperHigh
;		LDA $00
;		ORA #$0801
;
;	.Write
;		STA [!HDMA_Output],y : INY #2
;
;	.End
;		LDA #$0000 : STA [!HDMA_Output],y
;		PLX
;		LDA !HDMA_Output : STA !HDMA2source,x
;		SEP #$20
;		LDA !HDMA_Output+2 : STA $4324,x
;		PLD
;		RTL


; must be run after water projection
	Engine_WaterSkyGradient:
		LDA.w #Logic_ProjectionSkyGradient : STA $3180
		LDA.w #Logic_ProjectionSkyGradient>>8 : STA $3181
		JSR.w MPU_HDMA_1p4
		RTL

; must be run after water projection
	Engine_WaterGradient:
		LDA.w #Logic_ProjectionGradient : STA $3180
		LDA.w #Logic_ProjectionGradient>>8 : STA $3181
		JSR.w MPU_HDMA_1p4
		RTL



; can be run at any time, only cares about water level
; this module splits its RAM into 4, instead of 2
; the RAM is still contiguous, starting at location
; each section is size bytes long
; the first two sections are double buffered HDMA tables
; the last two sections are double buffered scroll values pointed to by the indirect tables

; scratch:
;	$00	24-bit pointer to offset data
;	$03	24-bit pointer to current working offset data in RAM
;	$06	counter - BG1 Y
;	$08	working scanline count for wave section
	Engine_WaterWaveEffect:
		PHD
		LDA #$3100 : TCD
		LDA $3000 : STA $00
		LDA $3000+1 : STA $00+1
		LDA !HDMA2init,x
		AND #$00FF : BNE .Main

	.Init
		LSR !HDMA2size,x					; halve size on init, splitting the table into 2

	.Main
		LDA $00							;\
		CLC : ADC #$0005					; | $00 = 24-bit pointer to offset data
		STA $00							;/
		LDA !HDMA2location+1,x
		STA $03+1
		STA !HDMA_Output+1
		LDA !HDMA2size,x
		ASL A
		ADC !HDMA2location,x
		STA $03
		LDA !HDMA2counter,x
		AND #$0001 : BEQ +
		LDA !HDMA2size,x
		ADC $03
		STA $03
		LDA !HDMA2size,x
		ADC !HDMA_Output
		STA !HDMA_Output
		+

		LDY #$0E						;\
	-	LDA $1C							; |
		CLC : ADC $7888						; |
		CLC : ADC [$00],y					; |
		STA [$03],y						; | update scroll coordinates
		DEY #2							; |
		LDA $1A							; |
		CLC : ADC [$00],y					; |
		STA [$03],y						; |
		DEY #2 : BPL -						;/

	.PreCalc
		LDY #$00
	;	LDA !BigRAM+2 : BPL ..done
		LDA !Level+2
		SEC : SBC $1C
		BMI ..done
	;	SEC : SBC #$0070
	;	BMI ..high

	;	..low
	;	CLC : ADC #$0070
		CMP #$0080 : BCC ..chunk2
		BRA ..chunk1

	;	..high
	;	LDA !BigRAM+0
	;	CMP #$0080 : BCC ..chunk2

		..chunk1
		LSR A : PHA
		BCC $01 : INC A
		STA [!HDMA_Output]
		LDY #$01
		LDA $03 : STA [!HDMA_Output],y
		LDY #$03
		PLA
		..chunk2
		STA [!HDMA_Output],y
		INY
		LDA $03 : STA [!HDMA_Output],y
		INY #2
		..done

	.ProcessWave
		PHX
		PHP
		REP #$10
		LDA !HDMA2counter,x
		LSR #2
		SEC : SBC $1C
		SEC : SBC $7888
		STA $06
		AND #$000F : INC A
		STA $08

		LDA $06
		AND #$0030
		EOR #$0030
		LSR #4 : TAX
		CLC

		..loop
		LDA $08 : STA [!HDMA_Output],y
		INY
		TXA
		AND #$0003
		ASL #2
		ADC $03
		STA [!HDMA_Output],y
		INY #2
		LDA #$0010 : STA $08
		INX
		CPX #$000E : BCC ..loop

		PLP
		PLX

	.End
		LDA #$0000 : STA [!HDMA_Output],y
		LDA !HDMA_Output : STA !HDMA2source,x
		SEP #$20
		LDA !HDMA_Output+2
		STA $4324,x
		STA $4327,x
		INC !HDMA2counter,x

		PLD
		RTL




;==============================
;
; SA-1 LOGIC ENGINES
;
;==============================
; matching SNES transcription engines are found in Engine/MPU.asm

; these codes run in MPU format
; SA-1 handles calculations, while SNES continuously copies SA-1 output into its WRAM table
; this code is called from the camera routine (!HDMAptr), meaning that $3100-$313F is in use by SA-1's GM14 thread
; however, during that phase of GM14, SA-1 only uses the scratch area ($00-$0F) and frame counters ($13-$14)
; this means that $3110-$3112 and $3115-$313F are free to use in this code


; i need a convenient way of setting a channel's output table (along with double-buffer offset)
; possibly just use the unused space in SNES page $01?



; proper procedure for a logic engine is:
;		PHP
;		PHB
;		PHD
;		JSR LogicEngineStart


	LogicEngineStart:
		REP #$30						; all regs 16-bit
		LDA #$3100 : TCD					; DP optimization
		LDA $3000						;\
		CLC : ADC #$0005					; |
		STA !HDMA_Input						; |
		TAY							; | get module data
		SEP #$20						; |
		LDA $3000+2 : STA !HDMA_Input+2				; |
		PHA : PLB						;/
		REP #$30						; all regs 16-bit
		LDX #$0000						; start at buffer 1
		LDA !HDMA_Output : STA !HDMA_WorkingOutput		; copy output to DP
		RTS


; use this macro to sync program state with SNES side whenever SA-1 should start writing a new buffer

	macro HDMA_SyncMPU()
	-	BIT !HDMA_ProgramState-1 : BPL -			; wait for SNES to spin
		TXA							;\ update buffer index
		EOR #$0008 : TAX					;/
		BNE ?state2						;\
		?state1:						; |
		STZ !HDMA_ProgramState : BRA ?sync			; | update program state
		?state2:						; |
		LDA #$8000 : STA !HDMA_ProgramState			; |
		?sync:							;/
	endmacro












; input:
;	!HDMA_Input = 24-bit pointer to HDMA table
;	format, for each chunk, is as follows:
;	- scanline count (16-bit)
;	- fraction (3 16-bit numbers: loop value (512*divisor/factor), factor, divisor)
;	table ends on a scanline count of 0x0000
	Logic_BG2Parallax:
		PHP
		PHB
		PHD
		JSR LogicEngineStart

	.PreCalc
		LDA $20							;\
		EOR #$FFFF : INC A					; | initial working position
		STA !HDMA_WorkingY					;/ (how many scanlines have to be skipped due to top of BG2 being off-screen)
		BMI ..loop
		CMP !HDMA_MaxY : BCS ..extendtop
		..loop
		LDA $0000,y : BEQ ..extendbottom			; clause for if BG2 is scrolled so far that only the last chunk is visible
		CLC : ADC !HDMA_WorkingY				;\ update working Y pos
		STA !HDMA_WorkingY					;/
		BEQ ..keepscanning					;\
		BMI ..keepscanning					; | see if we have reached an on-screen coord
		JMP .Draw						;/
		..keepscanning						;\
		TYA							; |
		CLC : ADC #$0008					; | otherwise, input index +8 and loop
		TAY							; |
		BRA ..loop						;/
		..extendbottom
		TYA							;\
		SEC : SBC #$0008					; | read previous entry (scroll factors only)
		TAY							;/
		..extendtop
		LDA #$0001 : JMP .Draw

	.End
		STZ !HDMA_Buffer1_Lines,x				;\ finish table
		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x	;/
		%HDMA_SyncMPU()
		PLD							; restore DP
		PLB
		PLP
		RTL							; return

	.Loop
		TYA							;\
		CLC : ADC #$0008					; | next source table entry
		TAY							;/
		%HDMA_SyncMPU()
		LDA !HDMA_WorkingY					;\
		CMP !HDMA_MaxY : BCS .End				; | check for end of screen and update working Y
		ADC $0000,y						; |
		STA !HDMA_WorkingY					;/
		LDA $0000,y : BEQ .End					; get scanline count

	; A = scanline count
	.Draw
		STZ $2250						; prepare multiplication
		STA !HDMA_Buffer1_Lines,x				; scanline count
		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x	; output address
		CLC : ADC #$0003					;\ update output
		STA !HDMA_WorkingOutput					;/
		LDA $1E							;\	
	-	CMP $0002,y : BCC +					; |
		SBC $0002,y : BRA -					; | queue multiplication
	+	STA $2251						; |
		LDA $0004,y : STA $2253					;/
		STX !HDMA_WorkingIndex					;\ wait
		LDX #$0001						;/
		LDA $2306						; get product
		STX $2250						;\
		STA $2251						; | queue division
		LDA $0006,y : STA $2253					;/
		LDX !HDMA_WorkingIndex					;\ reload X index and waste some cycles
		NOP							;/
		LDA $2306 : STA !HDMA_Buffer1_Data,x			; write scroll value

		BRA .Loop						; loop





; input:
;	!HDMA_Input = 24-bit pointer to HDMA table
;	format is 16-bit byte count followed by a 16-bit factor (8.8 format) for each chunk
;	table length should match the header word
;
; output:
;	$0C	number of bytes written to skeleton table
;	!BigRAM	skeleton table, 4 bytes for each rendered chunk
;		first word is scanline count of chunk
;		second word is chunk's ID, which is its index to the factor table (0xFFFF for dummy chunks)
;
; projection variables:
;	c (level position of camera center, $1C + 0x0070)
;	wl (level position of water level)
;
; scratch:
;	$00		base YZ distance (wl-c)
;	$02		dummy coord (used for filling in empty chunks)
;	$04		cut flag (n-trigger, if set, the current chunk's YZ coordinate is treated as 0 for the purposes of calculating its scanline count)
;	$06		tempX
;	$08		tempY
;	$0A		table length
;	$0C		pointer to !BigRAM, incremented to output scanline counts
;	$0E		!HDMA_Input+table length (pointer to second table)
;	!HDMA_Misc	holds value read from ($0E)

	Logic_BG3Projection:
		PHP
		PHB
		PHD
		JSR LogicEngineStart

	.PreCalc
		STZ !HDMA_WorkingY					; start from scanline 0
		STZ $04							; cut flag

		LDA (!HDMA_Input) : STA $02				; dummy coord
		LDY #$0002 : LDA (!HDMA_Input),y : STA $0A		; table length
		LDY #$0004 : LDA (!HDMA_Input),y : STA $0E		; pointer to coordinate table
		LDA.w #!BigRAM : STA $0C				; pointer to where scanline table will be dumped
		LDA !HDMA_Input						;\
		CLC : ADC #$0006					; | repoint input to low projection factor table
		STA !HDMA_Input						;/
		LDY #$0000						; read table from the front

		STZ $2250						; set ALU to multiplication
		LDA $1C							;\
		CLC : ADC #$0078					; | check if camera is above or below projection
		CMP !Level+2 : BCC .LowProjection			; | (this has an extra 8px of leeway to make the transition work better with the SNES limitations)
		JMP .HighProjection					;/

	.LowProjection
		LDA !Level+2						;\
		SEC : SBC $1C						; |
		SEC : SBC #$0070					; | $00 = base YZ distance (wl-c)
		CMP #$FFFD						; |
		BCC $03 : LDA #$FFFE					; > minimum negative YZ distance is -2
		STA $00							;/

		LDA (!HDMA_Input),y : STA $2251				;\ f*yz
		LDA $00 : STA $2253					;/
		NOP
		LDA #$0070
		CLC : ADC $2307
		BEQ ..loop

		..fillerchunk1
		STA !HDMA_WorkingY
		STA ($0C)						;\ output skeleton chunk size
		INC $0C : INC $0C					;/
		CMP #$0080 : BCC ..fillerchunk2
		LSR A : STA !HDMA_Buffer1_Lines,x
		BCC $01 : INC A
		PHA
		LDA $02 : STA !HDMA_Buffer1_Data+2,x
		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x
		CLC : ADC #$0005
		STA !HDMA_WorkingOutput
		%HDMA_SyncMPU()
		PLA

		..fillerchunk2
		STA !HDMA_Buffer1_Lines,x
		LDA $02 : STA !HDMA_Buffer1_Data+2,x
		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x
		CLC : ADC #$0005
		STA !HDMA_WorkingOutput
		%HDMA_SyncMPU()

		LDA #$FFFF : STA ($0C)					;\ output skeleton chunk ID
		INC $0C : INC $0C					;/

		; $2251 = f
		; $2253 = YZ
		..loop
		LDA #$0070						;\
		CLC : ADC $2307						; | temp YZ
		STA $08							;/

		LDA $22 : STA $2253					;\
		LDA ($0E) : STA !HDMA_Misc				; | temp X + read display coord
		INC $0E : INC $0E
		LDA $2307 : STA $06					;/

		INY #2							;\
		CPY $0A : BCC ..calcchunk				; | if this is the last chunk, use a scanline count of 8
		LDA #$0008 : BRA ..sendchunk				;/

		..calcchunk
		LDA (!HDMA_Input),y : STA $2251				;\
		LDA $00 : STA $2253					; |
		NOP							; |
		LDA #$0070						; | scanline count = f+1*YZ - f*YZ
		CLC : ADC $2307						; |
		BIT $04 : BMI ..sendchunk				; |
		SEC : SBC $08						;/

		..sendchunk
		CMP #$0000 : BEQ ..next					; 0 = skip this chunk
		STA !HDMA_Buffer1_Lines,x				; send scanline count
		STA ($0C)						;\ output skeleton chunk size
		INC $0C : INC $0C					;/
		CLC : ADC !HDMA_WorkingY				;\ update working
		STA !HDMA_WorkingY					;/
		TYA							;\
		DEC #2 : STA ($0C)					; | output skeleton chunk ID
		INC $0C : INC $0C					;/
		LDA $06 : STA !HDMA_Buffer1_Data,x			; send X scroll
		LDA !HDMA_Misc						;\
		SEC : SBC $08						; | send Y scroll
		STA !HDMA_Buffer1_Data+2,x				;/
		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x	; send output
		CLC : ADC #$0005					;\ update output
		STA !HDMA_WorkingOutput					;/

		%HDMA_SyncMPU()

		STZ $04

		..next
		CPY $0A : BCS ..end
		JMP ..loop

		..end
		JMP .End


	.HighProjection
		LDA $22 : STA $2251
		LDA !Level+2
		SEC : SBC $1C
		STA $00
		LDA $0A
		DEC #2 : STA $06					; $06 = last index to read ($0A = index to end at)

		; search table for first chunk to have a factor greater than 1.0
		; place that chunk on wl
		; adjust so each chunk is 1 scanline tall, with y-position based on the 1.0 chunk
		; chunks before the 1.0 one are placed above
		; chunks after are placed below
		; coords are used as usual
		; last chunk is 8px tall

		..search
		LDA (!HDMA_Input),y
		CMP #$0100 : BCS ..found
		INY #2
		CPY $0A : BCC ..search
		; if this error somehow occurs, just let it flow
		..found

		TYA
		LSR A
		SEC : SBC $00
		BNE $03 : JMP ..renderfromtop
		EOR #$FFFF : INC A
		BMI ..cut
		CMP #$00E0
		BCC $03 : LDA #$00E0
		BRA ..fillerchunk1

		; A = number of scanlines above first water chunk
		; if A is positive, we need filler chunks
		; if A is 0, the water chunks start at the top
		; if A is negative, -A number of chunks have to be skipped
		; (if this cuts into the last chunk, it might be cut

		..cut
		EOR #$FFFF : INC A					;\ $04 = number of scanlines to cut
		STA $04							;/
		LDA $0A							;\
		LSR A							; | total height of projection = table length/2 +7 (last chunk is 8px instead of 1px)
		ADC #$0007						;/
		SEC : SBC $04						;\
		BCC +							; | if the whole projection is cut, just end the table
		BEQ +							;/
		; A = number of scanlines to show
		CMP #$0008 : BCS ..multi
		..lastonly
		STA !HDMA_Buffer1_Lines,x
		STA ($0C)
		INC $0C : INC $0C
		LDY $06
		LDA (!HDMA_Input),y : STA $2253
		TYA : STA ($0C)
		INC $0C : INC $0C
		LDA ($0E),y
		SEC : SBC !HDMA_Buffer1_Lines,x
		STA !HDMA_Buffer1_Data+2,x
		LDA $2307 : STA !HDMA_Buffer1_Data+0,x
		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x
		CLC : ADC #$0005
		STA !HDMA_WorkingOutput
		%HDMA_SyncMPU()
	+	JMP .End
		..multi
		LDA $04
		ASL A : TAY
		BRA ..loop

		..fillerchunk1
		STA !HDMA_WorkingY
		STA ($0C)
		INC $0C : INC $0C
		CMP #$0080 : BCC ..fillerchunk2
		LSR A : STA !HDMA_Buffer1_Lines,x
		BCC $01 : INC A
		PHA
		LDA $02 : STA !HDMA_Buffer1_Data+2,x
		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x
		CLC : ADC #$0005
		STA !HDMA_WorkingOutput
		%HDMA_SyncMPU()
		PLA
		..fillerchunk2
		STA !HDMA_Buffer1_Lines,x
		LDA $02 : STA !HDMA_Buffer1_Data+2,x
		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x
		CLC : ADC #$0005
		STA !HDMA_WorkingOutput
		%HDMA_SyncMPU()
		LDA #$FFFF : STA ($0C)
		INC $0C : INC $0C

		..renderfromtop
		LDY #$0000

		..loop
		LDA (!HDMA_Input),y : STA $2253
		LDA #$0001
		CPY $06
		BNE $03 : LDA #$0008
		STA !HDMA_Buffer1_Lines,x
		STA ($0C)
		INC $0C : INC $0C
		CLC : ADC !HDMA_WorkingY
		STA !HDMA_WorkingY
		TYA : STA ($0C)
		INC $0C : INC $0C
		LDA $2307 : STA !HDMA_Buffer1_Data+0,x
		LDA ($0E),y
		SEC : SBC !HDMA_WorkingY
		STA !HDMA_Buffer1_Data+2,x
		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x
		CLC : ADC #$0005
		STA !HDMA_WorkingOutput
		%HDMA_SyncMPU()
		INY #2
		CPY $0A : BCC ..loop




; REFERENCE: OLD BEAUTIFUL VERSION
; because of the SNES hardware, this only works with opaque layers but not water
;	.HighProjection
;		LDY #$0006 : LDA (!HDMA_Input),y : STA !HDMA_Input	; repoint input to high projection factor table
;
;		LDY $0A : DEY #2					; read table from the back
;		LDA (!HDMA_Input),y : STA $2251				;\ f*yz
;		LDA $00 : STA $2253					;/
;		NOP
;		LDA #$0070
;		CLC : ADC $2307
;		BMI ..precalcloop
;		BNE $03 : JMP ..loop
;
;		..fillerchunk1
;		STA !HDMA_WorkingY
;		STA ($0C)						;\ output skeleton chunk size
;		INC $0C : INC $0C					;/
;		CMP #$0080 : BCC ..fillerchunk2
;		LSR A : STA !HDMA_Buffer1_Lines,x
;		BCC $01 : INC A
;		PHA
;		LDA $02 : STA !HDMA_Buffer1_Data+2,x
;		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x
;		CLC : ADC #$0005
;		STA !HDMA_WorkingOutput
;		%HDMA_SyncMPU()
;		PLA
;
;		..fillerchunk2
;		STA !HDMA_Buffer1_Lines,x
;		LDA $02 : STA !HDMA_Buffer1_Data+2,x
;		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x
;		CLC : ADC #$0005
;		STA !HDMA_WorkingOutput
;		%HDMA_SyncMPU()
;
;		LDA #$FFFF : STA ($0C)					;\ output skeleton chunk ID
;		INC $0C : INC $0C					;/
;
;		BRA ..loop
;
;		..precalcloop
;		DEY #2 ;: BMI ..edgecase				;\
;		INC $0E : INC $0E
;		LDA (!HDMA_Input),y : STA $2251				; | loop until we find something that is on-screen
;		LDA $00 : STA $2253					; |
;		LDA #$0070						; |
;		CLC : ADC $2307						; |
;		BMI ..precalcloop					;/
;		BEQ ..loop						;
;		INY #2							;\
;		DEC $0E : DEC $0E
;		LDA (!HDMA_Input),y : STA $2251				; | otherwise, calculate how many scanlines to remove from the chunk, then proceed with case 3
;		LDA $00 : STA $2253					;/
;		DEC $04							; set cut flag
;		; if a chunk is cut off, its YZ position is treated as 0 for the purposes of calculating its scanline count
;		; HOWEVER, it retains its original YZ position for the purposes of calculating its Y position
;
;		; $2251 = f
;		; $2253 = YZ
;		..loop
;		LDA #$0070						;\
;		CLC : ADC $2307						; | temp YZ
;		STA $08							;/
;
;		LDA $22 : STA $2253					;\
;		LDA ($0E) : STA !HDMA_Misc				; | temp X + read display coord
;		INC $0E : INC $0E
;		LDA $2307 : STA $06					;/
;
;		DEY #2 : BPL ..calcchunk				;\ if this is the last chunk, use a scanline count of 8
;		LDA #$0008 : BRA ..sendchunk				;/
;
;		..calcchunk
;		LDA (!HDMA_Input),y : STA $2251				;\
;		LDA $00 : STA $2253					; |
;		NOP							; |
;		LDA #$0070						; | scanline count = f+1*YZ - f*YZ
;		CLC : ADC $2307						; |
;		BIT $04 : BMI ..sendchunk				; |
;		SEC : SBC $08						;/
;
;		..sendchunk
;		CMP #$0000 : BEQ ..next					; 0 = skip this chunk
;		STA !HDMA_Buffer1_Lines,x				; send scanline count
;		STA ($0C)						;\ output skeleton chunk size
;		INC $0C : INC $0C					;/
;		CLC : ADC !HDMA_WorkingY				;\ update working
;		STA !HDMA_WorkingY					;/
;		TYA							;\
;		INC #2 : STA ($0C)					; | output skeleton chunk ID
;		INC $0C : INC $0C					;/
;		LDA $06 : STA !HDMA_Buffer1_Data,x			; send X scroll
;		LDA !HDMA_Misc						;\
;		SEC : SBC $08						; | send Y scroll
;		STA !HDMA_Buffer1_Data+2,x				;/
;		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x	; send output
;		CLC : ADC #$0005					;\ update output
;		STA !HDMA_WorkingOutput					;/
;
;		%HDMA_SyncMPU()
;
;		STZ $04
;
;		..next
;		TYA : BMI ..end
;		JMP ..loop
;		..end


	.End
		LDA $0C
		SEC : SBC.w #!BigRAM
		STA $0C

		LDA #$0001 : STA !HDMA_Buffer1_Lines,x
		LDA $02
		SEC : SBC !HDMA_WorkingY
		STA !HDMA_Buffer1_Data+2,x
		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x
		CLC : ADC #$0005
		STA !HDMA_WorkingOutput
		%HDMA_SyncMPU()

		STZ !HDMA_Buffer1_Lines,x				;\ finish table
		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x	;/
		%HDMA_SyncMPU()
		PLD
		PLB
		PLP
		RTL


; input:
;	$0C	number of bytes in skeleton table at !BigRAM
; scratch:
;	$00	sky prio
;	$02	extended prio
;	$0C	input
	Logic_ProjectionPriority:
		PHP
		PHB
		PHD
		JSR LogicEngineStart

		LDA (!HDMA_Input) : STA $00				; sky prio
		LDY #$0002 : LDA (!HDMA_Input),y : STA $02		; extended prio
		LDA $0C : BNE $03 : JMP .ExtendedPriority		; if there are no chunks at all, just extend
		LDA !HDMA_Input						;\
		CLC : ADC #$0004					; | repoint pointer to per-chunk prio
		STA !HDMA_Input						;/
		LDY #$0000						; read table from index 0

	.SkyPriority
		LDA !BigRAM+2 : BPL ..done
		LDA !BigRAM+0
		CMP #$0080 : BCC ..chunk2
		..chunk1
		LSR A : PHA
		BCC $01 : INC A
		STA !HDMA_Buffer1_Lines,x
		LDA $00 : STA !HDMA_Buffer1_Data+0,x
		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x
		CLC : ADC #$0003
		STA !HDMA_WorkingOutput
		%HDMA_SyncMPU()
		PLA
		..chunk2
		STA !HDMA_Buffer1_Lines,x
		LDA $00 : STA !HDMA_Buffer1_Data+0,x
		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x
		CLC : ADC #$0003
		STA !HDMA_WorkingOutput
		%HDMA_SyncMPU()
		INY #4
		..done

	.ChunkPriority
		..loop
		LDA !BigRAM+0,y : STA !HDMA_Buffer1_Lines,x
		STY !HDMA_WorkingIndex
		LDA !BigRAM+2,y : TAY
		LDA (!HDMA_Input),y : STA !HDMA_Buffer1_Data+0,x
		LDY !HDMA_WorkingIndex
		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x
		CLC : ADC #$0003
		STA !HDMA_WorkingOutput
		%HDMA_SyncMPU()

		INY #4
		CPY $0C : BCC ..loop

	.ExtendedPriority
		LDA #$0001 : STA !HDMA_Buffer1_Lines,x
		LDA $02 : STA !HDMA_Buffer1_Data+0,x
		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x
		CLC : ADC #$0003
		STA !HDMA_WorkingOutput
		%HDMA_SyncMPU()

	.End
		STZ !HDMA_Buffer1_Lines,x
		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x
		%HDMA_SyncMPU()

		PLD
		PLB
		PLP
		RTL





; input:
;	$0C		number of bytes in skeleton table at !BigRAM
; scratch:
;	$06		temporarily holds scanline count or color index
;	$0C		input
	Logic_ProjectionSkyGradient:
		PHP
		PHB
		PHD
		JSR LogicEngineStart

		STZ !HDMA_WorkingY					; start from scanline 0

	.SkyGradient
		LDA !BigRAM+2 : BPL ..done				; if positive, there is no sky gradient on-screen
		..append
		LDA !BigRAM+0 : STA !HDMA_MaxY
		LDA (!HDMA_Input) : JSR AppendColor0Gradient
		..done

	.ExtendedGradient
		LDA #$00E0 : STA !HDMA_MaxY
		LDY #$0002
		LDA (!HDMA_Input),y : JSR AppendColor0Gradient

	.End
		STZ !HDMA_Buffer1_Lines,x				;\ finish table
		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x	;/
		%HDMA_SyncMPU()
		PLD
		PLB
		PLP
		RTL


; input:
;	A = pointer to gradient (must end with a 0 scanline)
;	!HDMA_WorkingY = starting Y coordinate (on-screen)
;	!HDMA_MaxY = ending Y coordinate (on-screen)
; output:
;	$00 = pointer to gradient
;	$06 is shredded, since it's used as scratch
;	!HDMA_WorkingY = !HDMA_MaxY
	AppendColor0Gradient:
		STA $00
		LDY #$0000

		.Loop
		LDA ($00),y
		AND #$00FF : BEQ .ExtendFinal

		..readinput
		INY
		STA $06
		CLC : ADC !HDMA_WorkingY
		CMP !HDMA_MaxY : BCC ..calcchunk
		LDA !HDMA_MaxY
		SEC : SBC !HDMA_WorkingY
		BNE $01 : INC A
		STA $06
		LDA !HDMA_MaxY : STA !HDMA_WorkingY
		BRA ..sendchunk

		..calcchunk
		STA !HDMA_WorkingY

		..sendchunk
		LDA $06 : STA !HDMA_Buffer1_Lines,x
		STZ !HDMA_Buffer1_Data+0,x
		LDA ($00),y : STA !HDMA_Buffer1_Data+2,x
		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x
		CLC : ADC #$0005
		STA !HDMA_WorkingOutput
		%HDMA_SyncMPU()
		LDA !HDMA_WorkingY
		CMP !HDMA_MaxY : BCS .Return
		INY #2 : BRA .Loop
		RTS

		.ExtendFinal
		DEY #2
		LDA !HDMA_MaxY
		SEC : SBC !HDMA_WorkingY
		CMP #$0080 : BCC ..chunk2
		..chunk1
		LSR A
		PHA
		BCC $01 : INC A
		STA !HDMA_Buffer1_Lines,x
		STZ !HDMA_Buffer1_Data+0,x
		LDA ($00),y : STA !HDMA_Buffer1_Data+2,x
		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x
		CLC : ADC #$0005
		STA !HDMA_WorkingOutput
		%HDMA_SyncMPU()
		PLA

		..chunk2
		STA !HDMA_Buffer1_Lines,x
		STZ !HDMA_Buffer1_Data+0,x
		LDA ($00),y : STA !HDMA_Buffer1_Data+2,x
		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x
		CLC : ADC #$0005
		STA !HDMA_WorkingOutput
		%HDMA_SyncMPU()

		.Return
		RTS


; input:
;	$0C	number of bytes in skeleton table at !BigRAM
; scratch:
;	$00	color index
;	$0C	input
	Logic_ProjectionGradient:
		PHP
		PHB
		PHD
		JSR LogicEngineStart

		LDA (!HDMA_Input)					;\ color index
		AND #$00FF : XBA : STA $00				;/
		INC !HDMA_Input						; update pointer
		LDY #$0000

	.PreCalc
		LDA !BigRAM+2 : BPL ..done				; if positive, there is no section above the projection
		..append
		LDA !BigRAM+0
		CMP #$0080 : BCC ..chunk2

		..chunk1
		LSR A
		PHA
		BCC $01 : INC A
		STA !HDMA_Buffer1_Lines,x
		LDA $00 : STA !HDMA_Buffer1_Data+0,x
		ASL A : TAY
		LDA !PaletteRGB,y : STA !HDMA_Buffer1_Data+2,x
		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x
		CLC : ADC #$0005
		STA !HDMA_WorkingOutput
		%HDMA_SyncMPU()
		PLA

		..chunk2
		STA !HDMA_Buffer1_Lines,x
		LDA $00 : STA !HDMA_Buffer1_Data+0,x
		ASL A : TAY
		LDA !PaletteRGB,y : STA !HDMA_Buffer1_Data+2,x
		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x
		CLC : ADC #$0005
		STA !HDMA_WorkingOutput
		%HDMA_SyncMPU()
		LDY #$0004
		..done


	.ChunkColors
		..loop
		LDA !BigRAM+0,y : BEQ ..next
		STY !HDMA_WorkingIndex
		STA !HDMA_Buffer1_Lines,x
		LDA $00 : STA !HDMA_Buffer1_Data+0,x
		LDA !BigRAM+2,y : TAY
		LDA (!HDMA_Input),y : STA !HDMA_Buffer1_Data+2,x
		LDY !HDMA_WorkingIndex
		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x
		CLC : ADC #$0005
		STA !HDMA_WorkingOutput
		%HDMA_SyncMPU()
		..next
		INY #4
		CPY $0C : BCC ..loop


	.End
		LDA #$0001 : STA !HDMA_Buffer1_Lines,x
		LDA $00 : STA !HDMA_Buffer1_Data+0,x
		ASL A : TAY
		LDA !PaletteRGB,y : STA !HDMA_Buffer1_Data+2,x
		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x
		CLC : ADC #$0005
		STA !HDMA_WorkingOutput
		%HDMA_SyncMPU()

		STZ !HDMA_Buffer1_Lines,x				;\ finish table
		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x	;/
		%HDMA_SyncMPU()
		PLD
		PLB
		PLP
		RTL



; input:
;	$3100 = scroll offset (16-bit), uses same directions as layer, meaning that + will move the table up and - will move it down
;	$3102 = stretch value (16-bit), added to each scanline count
;	!HDMA_Input = 24-bit pointer to HDMA table
;	format, for each chunk, is as follows:
;	- scanline count (16-bit)
;	- value (8-bit)
;	table ends on a scanline count of 0x00
	Logic_HDMA_1p1:
		PHP
		PHB
		PHD
		JSR LogicEngineStart

	.PreCalc
		LDA $00							;\
		EOR #$FFFF : INC A					; | initial working position
		STA !HDMA_WorkingY					;/ (how many scanlines have to be skipped due to top of effect being off-screen)
		BMI ..loop
		CMP !HDMA_MaxY : BCS ..extendtop			; check if chunk is scrolled below screen
		..loop
		LDA $0000,y						;\ clause for if table is scrolled so far that only the last chunk is visible
		AND #$00FF : BEQ ..extendbottom				;/
		CLC : ADC $02						; add stretch value
		ADC !HDMA_WorkingY					;\ update working Y pos
		STA !HDMA_WorkingY					;/
		BEQ ..keepscanning					;\
		BMI ..keepscanning					; | see if we have reached an on-screen coord
		JMP .Draw						;/
		..keepscanning						;\ otherwise, input index +2 and loop
		INY #2 : BRA ..loop					;/
		..extendbottom
		DEY #2							; read previous entry (data)
		..extendtop
		LDA #$0001 : JMP .Draw

	.End
		STZ !HDMA_Buffer1+0,x					;\ finish table
		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x	;/
		%HDMA_SyncMPU()
		PLD							; restore DP
		PLB
		PLP
		RTL							; return

	.Loop
		INY #2							; read index +2
		%HDMA_SyncMPU()
		LDA !HDMA_WorkingY					;\
		CMP !HDMA_MaxY : BCS .End				; |
		LDA $0000,y						; |
		AND #$00FF : BEQ .End					; | check for end of screen and update working Y
		CLC : ADC !HDMA_WorkingY				; |
		ADC $02							; |
		STA !HDMA_WorkingY					;/
		LDA $0000,y						;\
		AND #$00FF						; | get scanline count + stretch value
		ADC $02							;/

	; A = scanline count
	.Draw
		CMP !HDMA_MaxY : BCC +					;\ cap at max, even with stretch
		LDA !HDMA_MaxY : +					;/
		CMP #$0080 : BCC ..single				; check for split line
		..split							;\
		LSR A : STA !HDMA_Buffer1+0,x				; |
		BCC $01 : INC A						; |
		PHA							; | generate split line
		LDA $0001,y : STA !HDMA_Buffer1+1,x			; |
		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x	; |
		INC #2 : STA !HDMA_WorkingOutput			;/
		%HDMA_SyncMPU()
		PLA							; scanline count for second chunk
		..single
		STA !HDMA_Buffer1+0,x					;\
		LDA $0001,y : STA !HDMA_Buffer1+1,x			; | generate chunk
		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x	;/
		INC #2 : STA !HDMA_WorkingOutput			; output+2
		BRA .Loop						; loop






; input:
;	!HDMA_Input = 24-bit pointer to HDMA table
;	format, for each chunk, is as follows:
;	- scanline count (8-bit)
;	- maximum brightness (8-bit)
;	table ends on a scanline count of 0x00
	Logic_Darkness:
		PHP
		PHB
		PHD
		JSR LogicEngineStart

	.PreCalc
		LDA !2100						;\
		AND #$00FF						; |
		CMP #$0080						; | $00 = maximum brightness value (global)
		BCC $03 : LDA #$0000					; |
		STA $00							;/
		BRA .Draw

	.Loop
		INY #2							; next source table entry
		%HDMA_SyncMPU()

	.Draw
		LDA !HDMA_WorkingY					;\
		CMP !HDMA_MaxY : BCS .End				; |
		LDA $0000,y						; | check for end of screen and update working Y
		AND #$00FF : BEQ .End					; |
		CLC : ADC !HDMA_WorkingY				; |
		STA !HDMA_WorkingY					;/
		LDA $0000,y : STA !HDMA_Buffer1+0,x			;\
		LDA $0001,y						; |
		AND #$00FF						; |
		CMP $00							; | generate chunk
		BCC $02 : LDA $00					; | (taking the lower brightness value)
		STA !HDMA_Buffer1+1,x					; |
		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x	;/
		INC #2 : STA !HDMA_WorkingOutput			; output+2
		BRA .Loop						; loop

	.End
		STZ !HDMA_Buffer1+0,x					;\ finish table
		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x	;/
		%HDMA_SyncMPU()
		PLD							; restore DP
		PLB
		PLP
		RTL							; return







; input:
;	!HDMA_Input = 24-bit pointer to HDMA table
;	format, for each chunk, is as follows:
;	- scanline count (16-bit)
;	- fraction (3 16-bit numbers: loop value (512*divisor/factor), factor, divisor)
;	table ends on a scanline count of 0x0000
;
; $00 = loop counter
; $02 = flip EOR
; $04 = flip add
; $0D = 24-bit pointer to !TrigTable
	Logic_DizzyEffect_BG1:
		PHP
		PHB
		PHD
		JSR LogicEngineStart

		LDA.w #!TrigTable : STA $0D
		LDA.w #!TrigTable>>8 : STA $0D+1


	.PreCalc
		REP #$20
		LDA !Level+2 : BEQ +
		DEC !Level+2 : +
		STZ $02
		STZ $04
		LDA $1A
		LSR #3
		EOR #$FFFF
		CLC : ADC !Level+2
		ASL #3
		AND #$03FF
		CMP #$0200 : BCC ..noflip
		..flip
		DEC $02
		INC $04
		..noflip
		AND #$01FF : TAY

		LDA !Level+2					;\
		CMP #$03E0 : BCC ..nowindup			; |
		..windup					; |
		SEC : SBC #$0400				; |
		EOR #$FFFF : INC A				; |
		BRA ..set					; |
		..nowindup					; | intensity
		CMP #$0100					; |
		BCC $03 : LDA #$0100				; |
		LSR #3						; |
		..set						; |
		STZ $2250					; |
		STA $2251					;/
		LSR #2 : STA !CutsceneSmoothness
		LDA #$003E : STA $00
		LDX #$0000


	.Loop
		LDA $1A
		AND #$01FF
		ORA #$2000
		STA !HDMA_Buffer1_Data+0,x

		LDA [$0D],y
		LSR #5 : STA $2253
		BRA $00 : NOP
		LDA $2306
		LSR #4
		EOR $02						; flip (EOR)
		CLC : ADC $1C
		CLC : ADC $7888
		CLC : ADC $04					; flip (add)
		AND #$01FF
		ORA #$2000
		STA !HDMA_Buffer1_Data+2,x

		TYA
		CLC : ADC #$0020
		AND #$01FF
		TAY
		CMP #$0020 : BCS +
		LDA $02
		EOR #$FFFF : STA $02
		LDA $04
		EOR #$0001 : STA $04
		+

		%HDMA_SyncMPU()

		DEC $00
		DEC $00
		BPL .Loop


	.End
		LDA [$0D],y					;\ final column calc, will be used for direct control
		LSR #5 : STA $2253				;/

		INC !HDMA_Sync

		LDA $2306					;\
		LSR #4						; |
		EOR $02						; |
		CLC : ADC $1C					; | $00 = direct control Y value (DP 0)
		CLC : ADC $7888					; |
		CLC : ADC $04					; |
		AND #$01FF : STA $3000				;/

		.Color
		SEP #$20
		STZ.w !2130					; don't add subscreen, just add $2132
		LDA !Level+2					;\ check if dizzy is on
		ORA !Level+3 : BNE ..dizzy			;/
		..normal
		LDA #$20 : STA.w !2131				;\
		REP #$20					; |
		LDA !PaletteRGB+0 : STA !2132_RGB		; > backdrop setup
		STZ !Color0					; |
		BRA ..done					;/
		..dizzy
		LDA #$3F : STA.w !2131				; color math on everything
		REP #$20					;\ backdrop setting
		LDA !PaletteRGB+0 : STA !Color0			;/
		LDA !Level+2					;\
		LSR #2						; |
		AND #$003E : TAY				; | color value
		REP #$20					; |
		LDA (!HDMA_Input),y : STA !2132_RGB		;/
		..done

		PLD						; restore DP

		STZ $22
		STZ $24

		.Mosaic
		SEP #$30
		LDA $14
		LSR A : BCC ..done
		LDA !Mosaic
		CMP #$10 : BCC ..done
		SEC : SBC #$10
		STA !Mosaic
		..done

		.MovePlayers
		LDY #$00
		..loop
		LDA !P2InAir-$80,y : BNE ..next
		REP #$20
		LDA !P2XPosLo-$80,y
		CLC : ADC #$0008
		SEC : SBC $1A
		LSR #3
		ASL A : TAX
		LDA !DecompBuffer+$1040,x
		SEC : SBC $1C
		SEC : SBC $7888
		SEP #$20
		STA !P2VectorX-$80,y
		LDA #$00 : STA !P2VectorAccX-$80,y
		LDA #$10 : STA !P2VectorTimeX-$80,y
		..next
		CPY #$80 : BEQ ..done
		LDY #$80 : BRA ..loop
		..done

		LDA #$13 : STA !MainScreen
		LDA #$04 : TRB !SubScreen
		LDA #$01 : STA !DizzyEffect

		PLB
		PLP
		RTL						; return



; input:
; $00 = loop threshold
	Logic_DizzyEffect_BG2:
		PHP
		PHB
		PHD
		JSR LogicEngineStart

	.PreCalc
		STZ !HDMA_WorkingY					; start from scanline 0
		LDA !Level+2						;\
		CMP #$03E0 : BCC ..nowindup				; |
		..windup						; |
		SEC : SBC #$0400					; |
		EOR #$FFFF : INC A					; |
		BRA ..set						; |
		..nowindup						; | intensity
		CMP #$0100						; |
		BCC $03 : LDA #$0100					; |
		LSR #3							; |
		..set							; |
		STZ $2250						; |
		STA $2251						;/
		LDA !Level+6
		INC A
		CMP.w #DizzyEffect_BG2_End-DizzyEffect_BG2-5
		BCC $03 : LDA #$0000
		STA !Level+6						;\
		CLC : ADC $20						; | modulo
	-	CMP.w #DizzyEffect_BG2_End-DizzyEffect_BG2-5 : BCC +	; |
		SBC.w #DizzyEffect_BG2_End-DizzyEffect_BG2-5 : BRA -	;/
	+	ADC !HDMA_Input
		TAY
		LDA !HDMA_Input						;\
		CLC : ADC.w #DizzyEffect_BG2_End-DizzyEffect_BG2-5	; | $00 = loop threshold
		STA $00							;/
		BRA .Draw


	.Loop
		INY							; read index +1
		CPY $00 : BCC +						;\ wrap from highest to lowest
		LDY !HDMA_Input : +					;/
		%HDMA_SyncMPU()

	.Draw
		LDA $0000,y						;\
		AND #$00FF : STA $2253					; |
		LDA #$0001 : STA !HDMA_Buffer1_Lines,x			; |
		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x	; |
		CLC : ADC #$0003					; | construct HDMA chunk
		STA !HDMA_WorkingOutput					; |
		LDA $2306						; |
		LSR #5 : ADC $20					; |
		STA !HDMA_Buffer1_Data,x				;/
		INC !HDMA_WorkingY					;\
		LDA !HDMA_WorkingY					; | step through entire screen
		CMP !HDMA_MaxY : BCC .Loop				;/

	.End
		STZ !HDMA_Buffer1_Lines,x				;\ finish table
		LDA !HDMA_WorkingOutput : STA !HDMA_Buffer1_Output,x	;/
		%HDMA_SyncMPU()
		PLD
		PLB
		PLP
		RTL








; list of HDMA effects




;==================================================
;		U N S O R T E D
;==================================================
; level		effect			channels
;--------------------------------------------------
; 000
;--------------------------------------------------
; 025		tinker shop		???
;--------------------------------------------------
; 1F0
;--------------------------------------------------
; 1F1
;--------------------------------------------------
; 1F2
;--------------------------------------------------
; 1F3
;--------------------------------------------------
; 1F4
;--------------------------------------------------
; 1F5
;--------------------------------------------------
; 1F6
;--------------------------------------------------
; 1F7
;--------------------------------------------------
; 1F8
;--------------------------------------------------
; 1F9
;--------------------------------------------------
; 1FA
;--------------------------------------------------
; 1FB
;--------------------------------------------------
; 1FC
;--------------------------------------------------
; 1FD
;--------------------------------------------------
; 1FE
;--------------------------------------------------
; 1FF
;--------------------------------------------------



;==================================================
;		R E A L M   1
;==================================================
; level		effect			channels
;--------------------------------------------------
; 001
;--------------------------------------------------
; 002
;--------------------------------------------------
; 003		parallax		1
;--------------------------------------------------
; 004		parallax		1
;		fuzzy			3
;					4 total
;--------------------------------------------------
; 005		parallax		1
;--------------------------------------------------
; 006		parallax		1
;		2132			3
;					4 total
;--------------------------------------------------
; 00C		BG3 projection		1
;		BG1 wave		1
;		color 0			1
;		priority		1
;					4 total
;--------------------------------------------------
; 026
;--------------------------------------------------
; 027		screen brightness	1
;--------------------------------------------------
; 02A
;--------------------------------------------------
; 02B		parallax		1
;--------------------------------------------------
; 02C
;--------------------------------------------------
; 02D		BG2 scroll
;--------------------------------------------------
; 02E
;--------------------------------------------------
; 02F
;--------------------------------------------------
; 032		collapse		3
;		- BG1 X
;		- BG2 X
;		- windowing
;		2132			3
;					6 total
;--------------------------------------------------
; 033
;--------------------------------------------------
; 038
;--------------------------------------------------
; 039		BG1 wave		1
;--------------------------------------------------




;==================================================
;		R E A L M   2
;==================================================
; level		effect			channels
;--------------------------------------------------
; 007		parallax		1
;--------------------------------------------------
; 008		parallax		1
;--------------------------------------------------
; 009
;--------------------------------------------------
; 00A		parallax		1
;--------------------------------------------------
; 00B		BG2 scroll		0
;--------------------------------------------------
; 00D		BG2 projection		1
;--------------------------------------------------
; 014
;--------------------------------------------------
; 028
;--------------------------------------------------
; 029
;--------------------------------------------------
; 030		parallax		1
;--------------------------------------------------
; 031
;--------------------------------------------------
; 034
;--------------------------------------------------





;==================================================
;		R E A L M   4
;==================================================
; level		effect			channels
;--------------------------------------------------
; 00F		parallax		2 (but only needs 1)
;--------------------------------------------------
; 010		BG2 scroll		0
;		special setpiece	2
;					2 total
;--------------------------------------------------
; 011
;--------------------------------------------------
; 012
;--------------------------------------------------
; 013		parallax		2 (but only needs 1)
;--------------------------------------------------
; 035		FULL 3D WATER		5
;		- BG3 projection
;		- BG2 projection
;		- BG1 wave
;		- color 0
;		- priority
;--------------------------------------------------
;





; to add:
; - HDMA tables
; - super-dynamic GFX areas



; LoRAM
; $0000-$007F		scratch for shader (only around 32 bytes are used)
; $0080-$00AD		used by status bar (prop + colors)
; $00AE-$00FF		----
; $0100-$01FF		SNES DP for MPU op
; $0200-$0DFF		----
; $0E00-$0FFF		shader code
; $1000-$1DFF		----
; $1E00-$1E1F		shader regs
; $1E20-$1E7F		----
; $1E80-$1EFF		various RAM codes
; $1F00-$1F0B		$43X2 mirrors for HDMA channles 2-7
; $1F0C			$420C double mirror
; $1F0D-$1FFF		SNES stack

; bank $7E
; $0000-$1FFF		LoRAM
; $2000-$ACFF		----
; $AD00-$C7FF		AN2
; $C800-$EDFF		----
; $EE00-$FBFF		backup of BG3 GFX during text box
; $FC00-$FFFF		shader output

; bank $7F
; $0000-$AFFF		----	at RESET: 0x6B written to $8182; 0x00,00,FF written to $837B-$737D
; $B000-$B3FF		AddmusicK data (can be moved with a define)
; $B400-$BFFF		----
; $C000-$C0FF		Lunar magic functions, notably exanimation
; $C100-$FFFF		----

; BWRAM image
; [ TO DO ]

; bank $40
; $0000-$1FFF		BWRAM image
; $2000-$3FFF		CCDMA area
; $4000-$43FF		last KiB of image cache, sometimes holds a layer 3 tilemap backup
; $4400-$447F		MSG data
; $4480-$44AF		----
; $44B0-$44BF		shader row disable (lasts 1 op only)
; $44C0-$44FF		square dynamo table (4 bytes per dynamic tile)
; $4500-$48FF		VR3 tables
; $4900-$49FF		debug: CPU tracker
; $4A00-$4DFF		RAM code area
; $4E00-$4E7F		player backup data
; $4E80			multiplayer flag
; $4E82-$4E83		----
; $4E84-$6FFF		various EMW variables
; $7000-$AFFF		main decompression buffer (holds layer 2 background tilemap during levels)
; $B000-$C7FF		----
; $C800-$FFFF		map16 table 1

; bank $41
; $0000-$7FFF		----
; $8000-$87FF		GFX/pal load status
; $8800-$89FF		----
; $8A00-$8AFE		sprite/shooter load status
; $8AFF			----
; $8B00-$8B5F		shield box data
; $8B60			shield exists flag
; $8B61-$8B64		shield hit by hitbox flags
; $8B65-$8EFF		----
; $8F00-$8FBF		platform data
; $8FC0			platform exists flag
; $8FC1-$8FF7		----
; $8FF8-$8FFF		index to OAM mirrors
; $9000-$99FF		OAM mirrors
; $9A00-$A0A3		particle data
; $A0A4-$A0AF		particle settings
; $A0B0-$A5AF		BG object data
; $A5B0-$ADAF		graphics data for map16 page 3
; $ADB0-$AFFF		----
; $B000-$BBFF		SRAM
; $BC00-$BFFF		SRAM buffer
; $C000-$C7FF		2D/3D cluster joint data
; $C800-$FFFF		map16 table 2


; EMW BWRAM variable listing
;
; load status/allocation	8 KiB
; RAM code area			1 KiB
; player backup data		128 B
; main decompression buffer	8 KiB used, needs space for at least 32 KiB
; sprite load status		< 256 B
; shield box data		< 256 B
; platform data			< 256 B
; OAM mirrors			10 KiB
; particle data			1.7 KiB
; BG object data		1.25 KiB
; Map16 page 3			2 KiB
; SRAM				3 KiB
; SRAM buffer			1 KiB (shouldn't this hold the !Level1-5 tables?)
; 2D/3D cluster joint data	8 KiB
; palette			3.75 KiB total
;	HSL main		0.75 KiB
;	HSL cache		0.75 KiB
;	HSL buffer		0.75 KiB
;	RGB cache		0.5 KiB
;	RGB buffer		0.5 KiB
;	shader input		0.5 KiB
; NPC talk table		1 KiB

; VR3-related variables should all be in the same bank
;	- CCDMA area
;	- image cache
;	- MSG RAM (because it works directly with image cache)
;	- shader row disable (usually set by direct CGRAM uploads)
;	- VR3 tables (VR2, CGRAM, tile update, CCDMA, square dynamo)
;	- RAM code area


; possible remap
; REQUIREMENTS:
;	- new object loader
;	- change !FreeRAM define in AMK
; bank $7E
; $0000-$1FFF		LoRAM
; $2000-$ACFF		super-dynamic GFX area 1
; $AD00-$C7FF		AN2
; $C800-$EDFF		super-dynamic GFX area 2
; $EE00-$FBFF		backup of BG3 GFX during text box
; $FC00-$FFFF		shader output

; bank $7F
; $0000-$BBFF		super-dynamic GFX area 3
; $BC00-$BFFF		AMK data (has to be moved)
; $C000-$C0FF		exanim data
; $C100-$FFFF		super-dynamic GFX area 4

; bank $40
; $0000-$1FFF		BWRAM image
; $2000-$3FFF		CCDMA area
; $4000-$43FF		last KiB of image cache
; $4400-$447F		MSG RAM
; $4480-$44BF		square dynamo table (4 byets per dynamic tile)
; $44C0-$44CF		shader row disable (lasts 1 op only)
; $44C0-$44FF		---- 64 B
; $4500-$48FF		VR3 tables
; $4900-$49FF		debug: CPU tracker
; $4A00-$4DFF		RAM code area
; $4E00-$6FFF		---- 8.25 KiB
; $7000-$AFFF		main decompression buffer (holds layer 2 background tilemap during levels)
; $B000-$C7FF		---- 6 KiB
; $C800-$FFFF		---- 14 KiB

; bank $41
; $0000-$07FF		GFX/pal load status
; $0800-$08FF		sprite load status
; $0900-$0964		shield boxes
; $0965-$09FF		---- 155 B
; $0A00-$0AC0		platforms
; $0AC1-$0AFF		---- 63 B
; $0B00-$11AF		particles
; $11B0-$11FF		---- 80 B
; $1200-$16AF		BG objects
; $16B0-$16FF		---- 80 B
; $1700-$17FF		---- 256 B
; $1800-$1FFF		Map16 page 3
; $2000-$29FF		OAM mirrors
; $2A00-$2A07		index to OAM mirrors
; $2A08-$2AFF		---- 248 B
; $2B00-$2FFF		---- 1.25 KiB
; $3000-$3FFF		SRAM (file 1 + file 2 + file 3 + permanent + buffer)
; $4000-$47FF		2D/3D cluster joint data
; $4800-$8FFF		---- 18 KiB
; $9000-$C7FF		map16 table 1
; $C800-$FFFF		map16 table 2

; tables are page-aligned, which is easier to read and often saves some CPU cycles
; misc EMW variables would be fit into the gaps
















